# Generated by Django 5.0.6 on 2024-06-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='milage',
        ),
    ]
